version: '3'
networks:
  deqlms:
    driver: bridge
services:
  deqlms:
    image: "geoworks/deql-ms-system"
    container_name: ms-system
    restart: always
    labels:
      org.label-schema.group: "deql-ms"
    environment:
      db_options_host: ms-postgis
      DEBUG: deql*
    networks:
      - deqlms
