version: '3'
networks:
  deqlms:
    driver: bridge
services:
################################
  ms-postgis:
    image: "mdillon/postgis"
    container_name: ms-postgis
    restart: always
    environment:
      POSTGRES_USER: mspostgis
      POSTGRES_PASSWORD: mspostgis
      POSTGRES_DB: postgis
    labels:
      org.label-schema.group: "ms-deps"
    ports:
     - "5445:5432"
    networks:
      - deqlms
################################
  ms-pgadmin:
    image: "dpage/pgadmin4"
    container_name: ms-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    labels:
      org.label-schema.group: "ms-deps"
    ports:
     - "6543:80"
    networks:
      - deqlms
################################
  ms-redis:
    image: "geoworks/redis"
    container_name: ms-redis
    restart: always
    labels:
      org.label-schema.group: "ms-deps"
    ports:
     - "32768:6379"
    networks:
      - deqlms
################################
